#!/bin/sh /etc/rc.common

START=19
USE_PROCD=1

CONF="coredns"
PROG="/usr/bin/coredns"

start_service() {
	config_load "$CONF"

	local enabled
	config_get_bool enabled "config" "enabled" "0"
	[ "$enabled" -eq 1 ] || return 1

	local config_file
	config_get config_file "config" "config_file" "/etc/coredns/Corefile"

	procd_open_instance "$CONF"
	procd_set_param command "$PROG"
	procd_append_param command -conf "$config_file"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn

	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}
